-- Datos Básicos 
SELECT DISTINCT 
  SPRIDEN_LAST_NAME APELLIDOS,
  RTRIM(SPRIDEN_FIRST_NAME||' '||SPRIDEN_MI) NOMBRES,
  SPBPERS_SEX SEXO,
  SPBPERS_SSN DOCUMENTO,
  SPRADDR_STREET_LINE1 DIRECCION
FROM SPRIDEN@PROD_MANOBI,
  SPRADDR@PROD_MANOBI,
  SPBPERS@PROD_MANOBI
WHERE SPRIDEN_PIDM = SPRADDR_PIDM (+)
  AND SPRIDEN_PIDM = SPBPERS_PIDM
  AND SPRADDR_STATUS_IND IS NULL
  AND SPRADDR_TO_DATE IS NULL
  AND SPRADDR_ATYP_CODE = 'RE'
  AND SPRIDEN_ID = '200818288'

-- Teléfono 

SELECT DISTINCT 
  SPRTELE_PHONE_NUMBER TELEFONO
FROM SPRIDEN@PROD_MANOBI,
  SPRTELE@PROD_MANOBI
WHERE SPRIDEN_PIDM = SPRTELE_PIDM
  AND SPRTELE_STATUS_IND IS NULL
  AND SPRIDEN_ID = '200818288'
  AND SPRTELE_TELE_CODE = 'RE'

-- Correo 
SELECT GOREMAL_EMAIL_ADDRESS EMAIL
FROM SPRIDEN@PROD_MANOBI,
  GOREMAL@PROD_MANOBI 
WHERE SPRIDEN_PIDM = GOREMAL_PIDM  (+)
  AND GOREMAL_EMAL_CODE = 'EUNI'
  AND SPRIDEN_ID = '200818288'
  
