DROP TABLE Co_Cuenta CASCADE CONSTRAINTS;

DROP TABLE Co_Banco CASCADE CONSTRAINTS ;

DROP TABLE Co_Convenio CASCADE CONSTRAINTS;

DROP TABLE Co_Dependencia CASCADE CONSTRAINTS;

DROP TABLE Co_Distribucion CASCADE CONSTRAINTS;

DROP TABLE Co_EstadoEstudiante CASCADE CONSTRAINTS;

DROP TABLE Co_Estudiante CASCADE CONSTRAINTS;

DROP TABLE Co_Materia CASCADE CONSTRAINTS;

DROP TABLE Co_Pago CASCADE CONSTRAINTS;

DROP TABLE Co_PeriodoAcademico CASCADE CONSTRAINTS;

DROP TABLE Co_PlanPagos CASCADE CONSTRAINTS;

DROP TABLE Co_PorcentajePagos CASCADE CONSTRAINTS;

DROP TABLE Co_TextoFormatoConvenio CASCADE CONSTRAINTS;

DROP TABLE Co_TipoLabor CASCADE CONSTRAINTS;

DROP TABLE Co_TipoMonitor CASCADE CONSTRAINTS;

DROP TABLE Co_TipoMonitorDependencia CASCADE CONSTRAINTS;
